export const TESTNET_NODE_URL = 'https://aptos.testnet.porto.movementlabs.xyz/v1'
export const MAINNET_NODE_URL = 'https://aptos.testnet.porto.movementlabs.xyz/v1'
export const TESTNET_FAUCET_URL = 'https://fund.testnet.porto.movementlabs.xyz'
export const MAINNET_INDEXER_URL = 'https://indexer.testnet.porto.movementnetwork.xyz/v1/graphql'
export const TESTNET_INDEXER_URL = 'https://indexer.testnet.porto.movementnetwork.xyz/v1/graphql'
